
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  isLoggedIn: false,
  isAdmin: false,
  userData: null
};

const authSlice = createSlice({
  name: "auth", // string: a unique name for the slice
  initialState, //initial state of this slice
  reducers:   // functions that take (state, action) and mutate state
  {  
    setUser(state, action) // action is an object that usually holds type field and payload field 
    {
      
      state.isLoggedIn = true;
      state.isAdmin = action.payload.isAdmin || false;
      state.userData = action.payload;      
    },
    clearUser(state) {
      state.isLoggedIn = false;
      state.isAdmin = false;
      state.userData = null;
    }
  }
});

export const { setUser, clearUser } = authSlice.actions;  //  Redux Toolkit automatically generates action creators for each reducer you define
                                                        /* 
                                                             1️⃣ authSlice.actions
                                                           {
                                                                setUser: function(payload) { return { type: "auth/setUser", payload }; },
                                                                clearUser: function(payload) { return { type: "auth/clearUser" }; }
                                                            }
                                                            Each function is an action creator: you call it with payload, it returns a properly formatted action object.
                                                        */
export default authSlice.reducer; //this exports the reducer function from the slice. The reducer function is automatically generated by createSlice.
                                  // authSlice.reducer is a single reducer function that knows how to handle all the actions defined in your reducers object.
                                    //You don’t write it manually — Redux Toolkit creates it for you. You use this reducer when configuring your Redux store