
import { createSlice } from "@reduxjs/toolkit";


// const product = { id:'', price:0, quantity:0, productTotal:0};


const initialState = {
  cartProducts :{},
  totalPrice:0
};

const cartSlice = createSlice({
  name: "cart", // string: a unique name for the slice
  initialState, //initial state of this slice
  reducers:   // functions that take (state, action) and mutate state
  {  
        updateProduct(state,action)
        {
            const productId = action.payload.id;
            state.cartProducts[productId] = action.payload;  
            
            let total =0;
            Object.entries(state.cartProducts).forEach(([key, prod]) => {
                    total += ( prod.price * prod.quantity);
            });
            state.totalPrice=total;
        }
        ,
        removeProduct(state,action)
        {
             const productId = action.payload.id;
             if (state.cartProducts[productId]) {
                delete state.cartProducts[productId];
                let total =0;
                Object.entries(state.cartProducts).forEach(([key, prod]) => {
                        total += ( prod.price * prod.quantity);
                });
                state.totalPrice=total;
             }
        },
        resetCart(state)
        {
          state.cartProducts = {};
          state.totalPrice = 0;
        }

   
  }
});

export const { updateProduct, removeProduct,resetCart } = cartSlice.actions;  //  Redux Toolkit automatically generates action creators for each reducer you define
                                                       
export default cartSlice.reducer; //this exports the reducer function from the slice. The reducer function is automatically generated by createSlice.
                                  // authSlice.reducer is a single reducer function that knows how to handle all the actions defined in your reducers object.
                                    //You don’t write it manually — Redux Toolkit creates it for you. You use this reducer when configuring your Redux store